language: python
python:
  - "3.6"
  - "3.7"
install:
  - pip install codecov pylint nosexcover pytlas
  - pip install -e ."[test]"
  - pip uninstall -y pytest
script:
  - pylint --rcfile .pylintrc pytlas_broker setup.py
  - python -m nose --with-doctest --with-xcoverage --cover-package=pytlas_broker
after_success:
  - codecov
